server = "localhost"
STATUS_INVALID = 2
STATUS_TERMINATED = -1
STATUS_FAILURE = 0
STATUS_SUCCESS = 1
status_msg = {STATUS_TERMINATED:"Terminated",STATUS_FAILURE:"Failure",STATUS_SUCCESS:"Success",STATUS_INVALID:"Invalid Operation"}
